### ISSUE TITLE
Won't compile on Travis osx

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/SARSOP.jl#15]
Can't get the tests for osx to compile on Travis. I don't have access to a Mac, so I'm not planning on fixing this.

It did work on Nina Hoopers Mac earlier today, so it might work for others.

**Comment by zsunberg** [comment]
The errors are C++ compile errors that seem to have to do with the visibility of iterator constructors (yay C++ ;)) This could possibly be fixed by using a different version of gcc or something

**Comment by jdechalendar** [comment]
This may have been addressed with the PR that I just opened.

**Comment by mykelk** [comment]
Awesome! @zsunberg and I will take a look.

**Comment by zsunberg** [comment]
fixed with #18
