### ISSUE TITLE
Issue with running SARSOP

### ISSUE THREAD

**Issue by WilliamJou** [JuliaPOMDP/SARSOP.jl#17]
I ran into this error while working with Zach on my implementation of a POMDP.

Below is my code, and the error states:

mode.pomdpx:line 394:
In State Function state1 : there are missing transitions
Transition not specified for instance a0 s20

https://gist.github.com/WilliamJou/8d28f48744b7231c4a816715e8dd8ec6

**Comment by zsunberg** [comment]
Thanks for posting! we will look into it.

**Comment by sarit-adh** [comment]
I am also facing the similar issue, even though transition function is returning something for each state, action pair. @WilliamJou did you manage to solve it?

**Comment by zsunberg** [comment]
This appears to be stale. closing.
