### ISSUE TITLE
Could not spawn -- no such file or directory

### ISSUE THREAD

**Issue by ajkeith** [JuliaPOMDP/SARSOP.jl#19]
I posted this to a pomdp-julia-users google group as well, not sure which place is more appropriate. Based on the discussion there, it seems like this was a known issue that has already been resolved on windows, so maybe my installation is incorrect and this isn't actually an issue.

Here's the code I'm trying to run from the crying babies demo from POMDPs.jl:

using POMDPs
using POMDPModels

POMDPs.add("SARSOP")
using SARSOP

bp = BabyPOMDP()
up = BabyBeliefUpdater(bp)
solver = SARSOPSolver()
p = solve(solver, bp)

and the error is:

could not spawn `'C:\Users\op\AppData\Local\JuliaPro-0.6.2.2\pkgs-0.6.2.2\v0.6\SARSOP\deps\appl\src\pomdpsol' model.pomdpx --output out.policy`: no such file or directory (ENOENT)
in solve at SARSOP\src\solver.jl:94
in #solve#5 at SARSOP\src\solver.jl:99
in run at base\process.jl:650
in #spawn#375 at base\process.jl:511
in setup_stdio at base\process.jl:499
in #376 at base\process.jl:512 
in _jl_spawn at base\process.jl:360

**Comment by MaximeBouton** [comment]
I think this is due to the appl folder being named " appl-0.96" on windows. 

This should be fixed by https://github.com/JuliaPOMDP/SARSOP.jl/commit/bfa0c2894773e1d33edf2e9105ed6a451becc5f1 
I included a renaming of the folder in the build script of the package.
Can you pull the latest version of SARSOP.jl and let us know if that worked? 
I will wait a bit before closing the issue.

**Comment by ajkeith** [comment]
Thanks for the speedy response!

I pulled the current version and got these build errors (I think I might
have had the same build errors for the older version too, I'm not sure). It
looks like the zip file name in the code matches that actual zip file name
in the deps folder.

Does the julia run function just send a command to the command line? I went
into the command line, cd'd to the deps folder, then ran "unzip
appl-0.96win.zip" and got the following error: "'unzip' is not recognized
as an internal or external command, operable program or batch file."


==========================================[ ERROR: SARSOP
]==========================================

LoadError: could not spawn `unzip appl-0.96win.zip`: no such file or
directory (ENOENT)
while loading
C:\Users\op\AppData\Local\JuliaPro-0.6.2.2\pkgs-0.6.2.2\v0.6\SARSOP\deps\build.jl,
in e
xpression starting on line 17

=====================================================================================================

==========================================[ BUILD ERRORS
]===========================================

WARNING: SARSOP had build errors.

 - packages with build errors remain installed in
C:\Users\op\AppData\Local\JuliaPro-0.6.2.2\pkgs-0.6
.2.2\v0.6
 - build the package(s) and all dependencies with `Pkg.build("SARSOP")`
 - build a single package by running its `deps/build.jl` script

**Comment by mykelk** [comment]
I think you need `unzip` on your Windows path. You'll need to add it and then restart Julia from a new terminal.

**Comment by ajkeith** [comment]
Ah okay, sounds like a setup on issue on my end. Thanks for the info.

If you have any references on how to add `unzip` to the windows path, it would be much appreciated - this is unfamiliar territory for me. (I did some googling, but I've only had luck finding info for separate tools like 7-zip rather than the native unzip in windows 10).
