### ISSUE TITLE
Problems getting SARSOP running

### ISSUE THREAD

**Issue by jamgochiana** [JuliaPOMDP/SARSOP.jl#25]
Hi,

I'm having problems getting the SARSOP solver running on a custom POMDP. FIB and QMDP are both solving fine. My packages all seem up to date.

I'm getting the following out:

(Working) Generating a pomdpx file: model.pomdpx

(Error) could not spawn `'C:\...\.julia\v0.6\SARSOP\deps\appl\src\pomdpsol' model.pomdpx --output out.policy`: no such file or directory (ENOENT)

Stacktrace:
 [1] _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::RawFD, ::RawFD, ::RawFD) at .\process.jl:360
 [2] #378 at .\process.jl:512 [inlined]
 [3] setup_stdio(::Base.##378#379{Cmd}, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:499
 [4] #spawn#377(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:511
 [5] run(::Cmd) at .\process.jl:650
 [6] #solve#5(::Bool, ::String, ::Function, ::SARSOP.SARSOPSolver, ::SinkholePOMDP, ::SARSOP.POMDPPolicy) at C:\...\.julia\v0.6\SARSOP\src\solver.jl:99
 [7] solve(::SARSOP.SARSOPSolver, ::SinkholePOMDP) at C:\...\.julia\v0.6\SARSOP\src\solver.jl:94

Any solutions?

Thanks,
Arec

**Comment by zsunberg** [comment]
Hi @jamgochiana , it looks like you are using windows and the SARSOP executable did not install directly. Does the file `C:\...\.julia\v0.6\SARSOP\deps\appl\src\pomdpsol` exist on your machine? What is the output of `julia> Pkg.build("SARSOP")`?

These issues may also be helpuful: https://github.com/JuliaPOMDP/SARSOP.jl/issues?utf8=%E2%9C%93&q=is%3Aissue+windows

Also, I'm assuming you are using Julia 0.6? I don't think SARSOP will work on 0.7/1.0 yet.

**Comment by jamgochiana** [comment]
I'm getting the error:

LoadError: could not spawn `unzip appl-0.96win.zip`: no such file or directory (ENOENT)
while loading C:\..\.julia\v0.6\SARSOP\deps\build.jl, in expression starting on line 17

which is weird since there is a zip file with that name in the deps folder. And yes Im using Julia 0.6 on Windows 

Thanks

**Comment by zsunberg** [comment]
I think "no such file or directory" is referring to unzip. Apparently your computer does not have the unzip program installed/accessible. You can look at deps\build.jl and do all those steps manually and the package should work after you have compiled SARSOP. (cd="change directory")

I don't know what the permanent solution is. Maybe use https://github.com/fhs/ZipFile.jl @MaximeBouton  @mykelk do you know what the right way to do this in windows is?

**Comment by mykelk** [comment]
I think the right way to do this is with https://github.com/JuliaPackaging/BinaryProvider.jl

This might be a fun first project for @jamgochiana ;-)

**Comment by MaximeBouton** [comment]
It seems to be working fine on windows now + we have CI with travis. 
Let's use #36 to discuss more about using BinaryBuilder
