### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by jeroenooms** [JuliaPOMDP/SARSOP.jl#4]
I can build the sarsop binaries on Mac and Linux, but not on Windows. From [build.js](https://github.com/JuliaPOMDP/SARSOP.jl/blob/master/deps/build.jl) it looks like this is supported? Has anyone been successful at compiling this with mingw-w64?

**Comment by mykelk** [comment]
I built the binaries using MSVC and posted them. I haven't tried mingw-w64. I tried it with cygwin a while ago, and I seem to recall that the MSVC version was a bit faster.

**Comment by jeroenooms** [comment]
Where did you post them? I would be interested in a copy :)

**Comment by jeroenooms** [comment]
Ah right they are here: http://web.stanford.edu/group/sisl/resources/appl-0.96-win-x64.zip. You don't happen to have a 32 builds by any chance?

**Comment by mykelk** [comment]
Yep, just posted them [here](http://web.stanford.edu/group/sisl/resources/appl-0.96-win-win32.zip). Feel free to modify the build script to detect 32 bit and file a PR.

**Comment by jeroenooms** [comment]
The win32 executables don't run on my machine due to a missing dll. The x64 executables don't have this dependency. Is it possible to build the 32bit executables without this dependency?
<img width="805" alt="screenshot" src="https://cloud.githubusercontent.com/assets/216319/14365069/09722a6e-fd0c-11e5-800b-734852610d47.PNG">

**Comment by jeroenooms** [comment]
Hmmm the win32 executables don't run on my machine due to a missing missing `MSVCP140.dll` and `VCRUNTIME140.dll`. The x64 executables depend on `MSVCP120.dll` and `MSVCR120.dll` which for whatever reason is present on my machine.

Would it be possible to build the 32 and 64 bit executables against the same VC runtime?




<img width="805" alt="screenshot" src="https://cloud.githubusercontent.com/assets/216319/14365069/09722a6e-fd0c-11e5-800b-734852610d47.PNG">

**Comment by mykelk** [comment]
I tried a static compile so you don't need those dependencies. Try redownloading and let me know if it works!

**Comment by jeroenooms** [comment]
Fantastic, this works. Do the 64bit executables have runtime dependencies? I think VS2013 runtime is installed on my system, so I can't check if it would work on a vanilla windows box.

**Comment by mykelk** [comment]
Just posted the 64 bit version without runtime dependencies.
