### ISSUE TITLE
pomdpsol.exe failure on Windows

### ISSUE THREAD

**Issue by bkraske** [JuliaPOMDP/SARSOP.jl#43]
While trying to run SARSOP recently, I get the following error:

ERROR: LoadError: failed process: Process(`'C:\Users\...\.julia\artifacts\c9b761df4aced3ca03c6751d6571b57e4f626e46\bin/pomdpsol.exe' model.pomdpx --output policy.out --precision 0.001 --trial-improvement-factor 0.5`, ProcessExited(3221225781)) [3221225781]

In attempting to directly run the pomdpsol.exe from file explorer, I get the following error:  libgcc_s_seh-1.dll (and separately) libstdc++-6.dll "was not found".

@MaximeBouton , @zsunberg suggested checking with you to see if you get similar errors.

**Comment by MaximeBouton** [comment]
Thank you for reporting, can you send the output of `] st` (with the SARSOP version specifically) and the julia version?  
Also do you have gcc installed on your machine? 

I am not able to reproduce locally unfortunately.

**Comment by bkraske** [comment]
I am running JuliaPro 1.5.1-1, although I had the same error in 1.5.2.-1.
Here is the output:
  [d96c9ae4] ARDESPOT v0.3.4
  [c52e3926] Atom v0.12.21 ⚲
  [8bb6e9a1] BeliefUpdaters v0.2.1
  [5ae59095] Colors v0.12.4
  [a81c6b42] Compose v0.9.1
  [e3df1716] D3Trees v0.3.1
  [4b033969] DiscreteValueIteration v0.4.4
  [31c24e10] Distributions v0.23.11
  [7073ff75] IJulia v1.21.3
  [e5e0dc1b] Juno v0.8.3 ⚲
  [e12ccd36] MCTS v0.4.4
  [442fdcdd] Measures v0.3.1
  [4c53ee00] POMCPOW v0.3.2
  [08074719] POMDPModelTools v0.3.2
  [355abbd5] POMDPModels v0.4.9
  [182e52fb] POMDPPolicies v0.3.3
  [e0d0a172] POMDPSimulators v0.3.8
  [92e6a534] POMDPTesting v0.2.5
  [c6f6ee83] POMDPXFiles v0.2.2 `https://github.com/JuliaPOMDP/POMDPXFiles.jl#master`
  [a93abf59] POMDPs v0.9.1
  [4722fa14] PkgAuthentication v0.3.0
  [91a5bcdd] Plots v1.6.5
  [3aa3ecc9] QMDP v0.1.4
  [8af83fb2] QuickPOMDPs v0.2.7
  [cef570c6] SARSOP v0.5.4
  [90137ffa] StaticArrays v0.12.4
  [44d3d7a6] Weave v0.10.3
  [9a3f8284] Random

It doesn't look like gcc is installed.

**Comment by MaximeBouton** [comment]
Maybe installing gcc would fix it, I am not sure where the missing dlls are from.

**Comment by zsunberg** [comment]
Yeah, it seems like there must be some implicit dependency we don't know about. It would be really nice to fix this so that we can use it in classes.

@MaximeBouton I am able to reproduce on a new windows vm. If you have time to troubleshoot and have access to a new windows install, you can probably reproduce with that.

@bkraske , perhaps one thing to try before installing gcc: `pkg> add SARSOP_jll@d32410b` (this will try to install an old version that used to work pretty reliably https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/tag/SARSOP-v0.96.0%2B0) if that works, we might be able to troubleshoot based on the difference between the two.

**Comment by bkraske** [comment]
Sure. I'll give it a try and let you know how it goes.

**Comment by bkraske** [comment]
pkg> add SARSOP_jll@d32410b returned an argument error: "invalid version range: "d32410b" ". Is there a different syntax I should use?

**Comment by zsunberg** [comment]
Sorry, it should have been a # instead of a @

**Comment by zsunberg** [comment]
but, I don't think that will work anyways. Maybe try

pkg> add https://github.com/JuliaPOMDP/SARSOP_jll.jl

**Comment by bkraske** [comment]
Installing via the link worked.
I was able to get SARSOP to run.

**Comment by zsunberg** [comment]
Wow, I am somewnat surprised! This was on Windows, right? @MaximeBouton I guess we just need to figure out what is different between the JuliaPOMDP and JuliaBinaryWrappers ones.

**Comment by bkraske** [comment]
Yeah, this was on Windows in JuliaPro_v1.5.1-1. 

Here's the version info for SARSOP, SAROP_jll if that's helpful
[cef570c6] SARSOP v0.5.4
[e478675d] SARSOP_jll v0.96.0+0 `https://github.com/JuliaPOMDP/SARSOP_jll.jl#master`

**Comment by MaximeBouton** [comment]
oh yeah I am surprised too but at least we cornered the problem nice catch. 
It might have something to do with the internals of BinaryBuilder because the build recipe and the source code did not change.

**Comment by zsunberg** [comment]
I think this works now because no one reported problems in the class (phew :sweat_smile: )
