### ISSUE TITLE
Doesn't work on Macs with M1 chips (?)

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/SARSOP.jl#50]
I am pretty sure that in DMU this year, this didn't work on maps with M1 chips.

Solving this will involve a fair amount of research into learning about binary builder if it is even possible to do it for M1s yet.

**Comment by jamgochiana** [comment]
Appears to be fixed (SARSOP PR for POMDPTools update ran tests on M1).

**Comment by zsunberg** [comment]
OK thanks @jamgochiana we'll see if it still works when people try to use it for DMU at stanford or CU

**Comment by dylan-asmar** [comment]
@zsunberg I think it works with the x86 architecture. However, it does not work with macOS ARM support with Julia v1.8

**Comment by zsunberg** [comment]
Ah, OK.

In the short term, @dylan-asmar or @jamgochiana, can one of you document this on the readme and point to instructions on how to use Rosetta? Do you have to have a separate Rosetta julia installation?

In the long term, it would be nice to get it to work on the M1 natively if someone wants to pick that up.

**Comment by dylan-asmar** [comment]
@zsunberg , I can try to get it working, but it is definitely an area I am only mildly familiar with.

**Comment by zsunberg** [comment]
Great, thanks! That would be very helpful. Let me know if I can help.

**Comment by zsunberg** [comment]
The julia artifact system seems pretty good, but it takes a bit to understand

**Comment by dylan-asmar** [comment]
Working on deploying the change now. https://github.com/JuliaPackaging/Yggdrasil/pull/5245.

**Comment by dylan-asmar** [comment]
@zsunberg I think it works now! I personally checked it on: 

- MacOS aarch64
- MacOS x86_64
- Linux x86_64

I also triggered the SARSOP tests again after the SARSOP_jll update and they all passed. However, I think that workflow is only set up for x86_64 Linux. With that said, I think it would be prudent to have a Windows user run the tests on SARSOP (and we should probably update the CI to include the architectures)

**Comment by zsunberg** [comment]
Cool, thanks for all your work on this! I set up the CI to run on Mac x64, Linux, and Windows. Not sure how to get aarch64 to work, but that is a separate issue.
