### ISSUE TITLE
error "Probabilities sum up to 0. It should sum up to 1"

### ISSUE THREAD

**Issue by rguptatx** [JuliaPOMDP/SARSOP.jl#7]
I extended the GridWorld example with observations. I get the error:
Probabilities sum up to 0. It should sum up to 1

here is a log:
WARNING
  model.pomdpx:Line 32:
  In Belief Function Tables state0
  In instance null
  Probabilities sum up to 0. It should sum up to 1
ERROR: LoadError: failed process: Process(`/.julia/v0.4/SARSOP/deps/appl-0.96/src/pomdpsol model.pomdpx --output out.policy`, ProcessExited(255)) [255]
 in run at ./process.jl:531
 in solve at /.julia/v0.4/SARSOP/src/solver.jl:100
 in solve at /.julia/v0.4/SARSOP/src/solver.jl:98
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading pgridworld.jl, in expression starting on line 498

Any pointers to what I am missing in code, or how to go about figuring out
source of error would be greatly appreciated.

**Comment by mykelk** [comment]
Can you post the model.pomdpx that gets generated? That might give us a hint.

**Comment by rguptatx** [comment]
model.pomdpx attached
[model.pomdpx.txt](https://github.com/JuliaPOMDP/SARSOP.jl/files/378500/model.pomdpx.txt)

**Comment by mykelk** [comment]
It appears that your initial belief state assigns zero probability to all states. This distribution should sum to 1.

**Comment by zsunberg** [comment]
This appears to be resolved or stale - closing
